import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const root = fileURLToPath(new URL('../dist/', import.meta.url));
await mkdir(root, { recursive: true });
const [stylesVersion, scriptVersion] = await Promise.all(['styles.css', 'site.js'].map(async filename => createHash('sha256').update(await readFile(`${root}${filename}`)).digest('hex').slice(0, 10)));
const origin = 'https://trinity-marshall-redesign.swishhyy.chatgpt.site';
const mission = 'is to educate and develop the whole individual in mind, body, and spirit in keeping with the love and teaching of Jesus Christ, our Lord and Savior.';
const vision = 'is to be preparing children ages three through eighth grade for a successful future, both academically, spiritually, and socially. Through a diverse and well-rounded curriculum, we achieve that goal every single day with every single student.';
const apply = 'https://tes-tx.client.renweb.com/oa/?memberid=1788';
const portal = 'https://logins2.renweb.com/logins/ParentsWeb-Login.aspx';
const give = 'https://trinityepiscopalschool-7.factsmgtadmin.com/give/';
const mail = 'mailto:mwilliams@trinitymarshall.net';
const tour = `${mail}?subject=Schedule%20a%20Trinity%20school%20tour`;
const official = 'https://www.trinitymarshall.org';
const readingTracker = 'https://global-pr-widgets.renaissance-go.com/widgets/v1/069e7290-351a-4dac-b5fb-0456b6cdbf06';
const readingImage = 'https://global-pr-widgetimages.renaissance-go.com/069e7290-351a-4dac-b5fb-0456b6cdbf06.png';
const icon = (type) => {
  const paths = {
    book: '<path d="M12 7c-3-2-6-2-9-1v13c3-1 6-1 9 1m0-13c3-2 6-2 9-1v13c-3-1-6-1-9 1V7Z"/>',
    calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-13 4h2m4 0h2"/>',
    people: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 4v3"/>',
    pin: '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
    file: '<path d="M14 2H5v20h14V7l-5-5Zm0 0v5h5M8 12h8m-8 4h6"/>',
    phone: '<path d="m5 3 4 1 1 5-3 2a14 14 0 0 0 6 6l2-3 5 1 1 4c-1 3-4 3-7 2C7 19 3 14 2 8 1 5 2 3 5 3Z"/>',
    mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>'
  };
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type]}</svg>`;
};
const button = (href, text, secondary = false) => `<a class="button${secondary ? ' button-secondary' : ''}" href="${href}">${text}</a>`;
const link = (href, text) => `<a class="text-link" href="${href}">${text}</a>`;
const resource = (href, title, text, type = 'file', detail = 'View resource') => `<a class="resource" href="${href}"><span class="resource-icon">${icon(type)}</span><span><strong>${title}</strong><span class="resource-description">${text}</span></span><span class="resource-action">${detail}</span></a>`;
const pageIntro = (label, title, subtitle) => `<section class="page-intro"><div class="container"><p class="eyebrow">${label}</p><h1>${title}</h1><p class="intro-text">${subtitle}</p></div></section>`;
const visit = () => `<section class="visit-section"><div class="container visit-inner"><div><p class="eyebrow">Come get to know us</p><h2>See Trinity for yourself.</h2><p>Meet our teachers, explore our classrooms, and ask your questions on a private school tour.</p></div><div class="visit-actions">${button('contact.html', 'Plan a visit')}${link('tel:+19039383513', '(903) 938-3513')}</div></div></section>`;

const pages = {
  'index.html': {
    title: 'Trinity Episcopal School | Marshall, Texas',
    description: 'Christian education for preschool through eighth grade in Marshall, Texas. Explore Trinity’s mission, programs, admissions, and family resources.',
    nav: 'home',
    content: `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Preschool through eighth grade · Marshall, Texas</p><h1>Educating the mind,<br>body, and <em>spirit.</em></h1><p>A strong academic foundation. A caring Christian community. A place for your child to learn, grow, and belong.</p><div class="button-row">${button('contact.html', 'Schedule a tour')}${button('admissions.html', 'Explore admissions', true)}</div><p class="hero-note">Welcoming families since 1954</p></div><figure class="hero-image"><img src="assets/trinity-life.jpg" width="1920" height="1080" alt="Trinity students in school uniforms gathered with a dog" fetchpriority="high"><figcaption>Growing together at Trinity</figcaption></figure></div></section>
    <section class="quick-links" aria-label="Frequently used links"><div class="container quick-grid"><a href="programs.html">${icon('book')}<span>Our programs<small>Find your child’s next chapter</small></span></a><a href="admissions.html#tuition">${icon('file')}<span>Tuition &amp; fees<small>2026–2027 school year</small></span></a><a href="calendar.html">${icon('calendar')}<span>School calendar<small>Plan for the year ahead</small></span></a><a href="parents.html">${icon('people')}<span>Parent resources<small>Everything in one place</small></span></a></div></section>
    <section class="section mission-section"><div class="container mission-grid"><div><p class="eyebrow">Faith at the heart of learning</p><h2>Our mission</h2><p class="mission-statement">${mission}</p></div><div class="mission-aside"><span class="section-number">01 / Our purpose</span><h3>The whole child.<br>Every day.</h3><p>Trinity brings academics, the arts, athletics, and spiritual growth together in a supportive school community.</p>${link('about.html', 'Get to know Trinity')}</div></div></section>
    <section class="section soft-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">A foundation for every stage</p><h2>Two programs. One Trinity family.</h2></div>${link('programs.html', 'Explore our programs')}</div><div class="program-grid"><article class="program-card"><img src="assets/preschool.jpg" width="606" height="450" alt="A preschool student participating in Texas Discovery Day" loading="lazy"><div class="program-copy"><p class="eyebrow">Ages 3 &amp; 4</p><h3>Preschool</h3><p>Early learning, creativity, and friendship in a Christian environment, with reading, math, art, music, and play.</p>${link('programs.html#preschool', 'Learn about preschool')}</div></article><article class="program-card"><img src="assets/school-life.jpg" width="1368" height="1824" alt="Trinity students playing drums in music class" loading="lazy"><div class="program-copy"><p class="eyebrow">Kindergarten – Grade 8</p><h3>Growing in knowledge &amp; character</h3><p>Challenging academics, individual attention, fine arts, and competitive sports, grounded in Christian values.</p>${link('programs.html#kinder-8', 'Learn about K–8')}</div></article></div><p class="section-footnote">After-school care is available until 5:30 p.m. for both programs.</p></div></section>
    <section class="section reading-section" id="reading" aria-labelledby="reading-title"><div class="container reading-grid"><div class="reading-copy"><p class="eyebrow">Accelerated Reader</p><h2 id="reading-title">Trinity reads!</h2><p>Follow our students’ monthly reading progress in books, words, and average reading time.</p>${link(readingTracker, 'View reading tracker')}</div><figure class="reading-widget"><a href="${readingTracker}" class="reading-tracker-link" aria-label="Open Trinity’s live Accelerated Reader tracker"><img src="${readingImage}" width="1200" height="615" alt="Trinity Episcopal School’s monthly reading totals from Accelerated Reader" loading="lazy" data-reading-tracker data-fallback="assets/reading-snapshot-2026-10-04.png" data-fallback-alt="October 2026 reading snapshot, captured October 4: 46 books, 258,674 words, and an individual student average of 60 minutes per day."></a><figcaption>Monthly school reading progress · Renaissance Accelerated Reader</figcaption><p class="reading-status" data-reading-status hidden>Live totals are unavailable. Showing the October 4, 2026 snapshot.</p></figure></div></section>
    <section class="section"><div class="container family-grid"><div><p class="eyebrow">For new and returning families</p><h2>A clear path to<br>your next step.</h2><p>Find enrollment information, everyday resources, and the people who can help.</p></div><div class="resource-list">${resource('admissions.html','Join the Trinity family','Application steps, requirements, tuition, and financial aid.','book','Admissions')}${resource('parents.html','Already part of Trinity?','FACTS, supply lists, uniforms, and the student handbook.','people','For parents')}${resource('contact.html','Let’s talk','Contact the school or arrange a private tour.','mail','Contact us')}</div></div></section>${visit()}`
  },
  'about.html': {
    title: 'About Trinity | Mission, Vision & History', description: 'Learn about Trinity Episcopal School’s mission, vision, Christian identity, and history of education in Marshall since 1954.', nav: 'about',
    content: `${pageIntro('Get to know Trinity','Rooted in faith.<br>Focused on your child.','Since 1954, Trinity Episcopal School has connected Christian character with academic excellence in Marshall, Texas.')}
    <section class="section"><div class="container purpose-grid"><article class="purpose-block"><p class="eyebrow">Our purpose</p><h2>Our Mission</h2><p class="purpose-statement">${mission}</p></article><article class="purpose-block vision-block"><p class="eyebrow">Our future</p><h2>Our Vision</h2><p class="purpose-statement">${vision}</p></article></div></section>
    <section class="section soft-section"><div class="container content-grid"><div><p class="eyebrow">Our story</p><h2>A Marshall tradition<br>since 1954.</h2></div><div class="prose"><p>Trinity was founded to cultivate Christian character and excellence in education. The school is a mission of <a href="https://www.trinityepiscopalmarshall.org/">Trinity Episcopal Church</a> in Marshall and serves children from age three through eighth grade.</p><p>Faith, learning, and community remain at the center of the school’s work. Trinity pairs a challenging curriculum with opportunities in fine arts, athletics, and spiritual development.</p><h3>A history of accreditation</h3><p>The school’s published history records initial Texas Education Agency accreditation in 1976, accreditation through the Southwestern Association of Episcopal Schools in 1989, and through the Southern Association of Colleges and Schools, now Cognia, in 2001.</p>${link(`${official}/about`, 'Read the school’s full accreditation history')}</div></div></section>
    <section class="section"><div class="container content-grid"><div><p class="eyebrow">A welcome from our Head of School</p><h2>Come see<br>what makes Trinity special.</h2><p class="signature">Carrie Hammack<span>Head of School</span></p></div><div class="prose"><p>Our school welcomes children from preschool through eighth grade into a community that values academic achievement, a healthy lifestyle, and spiritual growth.</p><p>We invite you to visit our classrooms, meet our faculty and staff, and learn how the arts, music, drama, and sports enrich each child’s school experience.</p>${button('contact.html', 'Arrange your visit')}</div></div></section>${visit()}`
  },
  'programs.html': {
    title: 'Programs | Preschool & Kindergarten–Eighth Grade', description: 'Explore Trinity’s preschool for ages 3 and 4, K–8 academics, fine arts, athletics, traditions, and after-school care.', nav: 'programs',
    content: `${pageIntro('Learning at Trinity','Room to discover.<br>Support to grow.','A Christian education that nurtures academic, creative, physical, and spiritual growth at every stage.')}<div class="container page-jumps"><a href="#preschool">Preschool</a><a href="#kinder-8">Kindergarten–Grade 8</a><a href="#school-life">Life at Trinity</a></div>
    <section class="section" id="preschool"><div class="container program-detail"><img class="detail-image" src="assets/preschool.jpg" width="606" height="450" alt="A Trinity preschool student at Texas Discovery Day"><div><p class="eyebrow">Ages 3 &amp; 4</p><h2>A joyful start<br>to learning.</h2><p>Preschool combines early academics with the social skills children develop as they learn, create, and make friends in a Christian setting.</p><ul class="feature-list"><li>Age-appropriate introductions to reading and math</li><li>Bible, technology, music, and library skills</li><li>Art and Body Rhythmics</li><li>After-school care until 5:30 p.m.</li></ul><p>Questions about preschool? Contact the school and ask for Preschool Director Eloise Lambright.</p>${button('contact.html','Ask about preschool')}</div></div></section>
    <section class="section soft-section" id="kinder-8"><div class="container program-detail reverse"><div><p class="eyebrow">Kindergarten – Grade 8</p><h2>Challenge, confidence,<br>and character.</h2><p>Trinity’s K–8 program combines a rigorous curriculum with support from caring teachers and staff. Students build knowledge while learning to contribute to their school community.</p><ul class="feature-list"><li>Academics that extend beyond state standards</li><li>Art, music, physical education, and Bible</li><li>Classroom technology and iPads in the upper grades</li><li>Theater and competitive athletics</li><li>After-school care until 5:30 p.m.</li></ul>${button('admissions.html', 'Explore K–8 admissions')}</div><img class="detail-image music-image" src="assets/school-life.jpg" width="1368" height="1824" alt="Trinity students working together in music class" loading="lazy"></div></section>
    <section class="section" id="school-life"><div class="container"><div class="section-heading"><div><p class="eyebrow">Beyond the classroom</p><h2>Life at Trinity</h2></div></div><div class="three-columns"><article class="text-column"><span class="section-number">01</span><h3>Fine arts &amp; athletics</h3><p>Students can explore art, music, and theater, with sports opportunities including volleyball, basketball, golf, and cross country.</p></article><article class="text-column"><span class="section-number">02</span><h3>Shared traditions</h3><p>World Bazaar, Chapel Buddies, Famous Persons, Pop’s Night Out, and Grandparent’s Day connect learning with the wider school family.</p>${link(`${official}/traditions`,'Read about our traditions')}</article><article class="text-column"><span class="section-number">03</span><h3>Learning beyond school</h3><p>Educational field trips give students opportunities to connect classroom learning with places, people, and experiences.</p>${link(`${official}/field-trips`,'Explore school field trips')}</article></div></div></section>${visit()}`
  },
  'admissions.html': {
    title: 'Admissions | Applications, Tuition & Financial Aid', description: 'Learn how to apply to Trinity Episcopal School, view 2026–2027 tuition, and find admissions requirements and financial assistance.', nav: 'admissions',
    content: `${pageIntro('Join the Trinity family','Your next chapter<br>starts here.','Registration for the 2026–2027 school year is open. Get to know the school, review the requirements, and begin your application.')}<div class="container page-jumps"><a href="#apply">How to apply</a><a href="#requirements">Requirements</a><a href="#tuition">Tuition &amp; fees</a><a href="#assistance">Financial assistance</a></div>
    <section class="section" id="apply"><div class="container"><div class="section-heading"><div><p class="eyebrow">Getting started</p><h2>A simple way forward.</h2></div></div><ol class="steps"><li><span class="step-number">01</span><h3>Visit the school</h3><p>Meet the Trinity community and talk about your child’s needs on a private tour.</p>${link('contact.html','Schedule your tour')}</li><li><span class="step-number">02</span><h3>Start your application</h3><p>Create an online account, begin a new student application, and return to it when you need to.</p>${link(apply,'Start a new student application')}</li><li><span class="step-number">03</span><h3>Complete the requirements</h3><p>Submit requested records and complete any required testing. Track your application in your online account.</p>${link('#requirements','Review admissions requirements')}</li></ol><div class="notice"><div><h3>Returning to Trinity?</h3><p>Use your existing FACTS Family Portal to complete enrollment.</p></div>${button(portal,'Returning student enrollment',true)}</div></div></section>
    <section class="section soft-section" id="requirements"><div class="container content-grid"><div><p class="eyebrow">Admissions requirements</p><h2>Finding the<br>right fit.</h2><p>Admission depends on an accepted application and the conditions established by the Board of Directors.</p></div><div class="prose"><h3>Kindergarten</h3><p>New kindergarten applicants complete a readiness test. A testing fee may apply.</p><h3>Grades 1–8</h3><p>Provide grades and testing records from previous schools. Applicants must complete an admissions test; a testing fee may apply. Where applicable, prior results should meet grade-level expectations, including passing Texas state tests, with above-average grades and good citizenship.</p><h3>For every applicant</h3><p>The school considers readiness, preparation, and motivation through testing, recommendations, and/or interviews.</p>${link(`${official}/admissions`,'Read the full school admissions policy')}</div></div></section>
    <section class="section" id="tuition"><div class="container"><div class="section-heading"><div><p class="eyebrow">2026–2027 school year</p><h2>Tuition &amp; fees</h2></div>${link('assets/tuition-2026-2027.jpg','View the complete tuition schedule')}</div><div class="table-wrap" role="region" aria-label="2026–2027 tuition rates" tabindex="0"><table><caption>Standard tuition and multi-child rates</caption><thead><tr><th scope="col">Program</th><th scope="col">Annual tuition</th><th scope="col">Monthly payment</th><th scope="col">Prepay in full</th></tr></thead><tbody><tr><th scope="row">Preschool</th><td>$3,240.00</td><td>$324.00</td><td>$3,175.20</td></tr><tr><th scope="row">Preschool · multi-child</th><td>$3,078.00</td><td>$307.80</td><td>$3,016.44</td></tr><tr><th scope="row">Kindergarten–Grade 8</th><td>$6,850.00</td><td>$685.00</td><td>$6,713.00</td></tr><tr><th scope="row">K–8 · multi-child</th><td>$6,507.50</td><td>$650.75</td><td>$6,377.35</td></tr></tbody></table></div><p class="small-text">Automatic payments are drafted on the 10th or 25th. The multi-child rate applies to children other than the oldest enrolled child. Full prepayment must be received by August 1 to qualify for the listed discount.</p><div class="two-columns tuition-notes"><article><h3>Enrollment &amp; grade-level fees</h3><p>New student enrollment is $200. Returning student enrollment is $200 when registered by May 31; after June 1, the listed fees are $300 for Pre-K and $400 for K–8.</p><p>Grade-level fees: $160 for Pre-K and $300 for K–8. Enrollment fees secure your child’s place; grade-level fees are due by August 1.</p></article><article><h3>Extended enrichment</h3><p>Monthly rates are $235 for Pre-K five days a week, $130 for Pre-K until 3 p.m. five days a week, and $130 for K–8 five days a week. Daily drop-in rates are $30 for Pre-K and $20 for K–8.</p><p>Contact the school to confirm availability and the arrangement that fits your family.</p></article></div></div></section>
    <section class="section soft-section" id="assistance"><div class="container content-grid"><div><p class="eyebrow">Support for families</p><h2>Financial assistance</h2></div><div class="prose"><h3>Financial aid &amp; scholarships</h3><p>Trinity’s aid and scholarship program is funded by private donations and foundation grants. Contact the school for details about availability and applying.</p>${link(`${official}/financial-aid-and-scholarships`,'School financial aid information')}<h3>Texas Education Freedom Accounts</h3><p>The school’s website states that Trinity accepts TEFA funds. Find the school’s application resources and contact the office with questions about using these funds.</p>${link(`${official}/texas-education-freedom-accounts`,'TEFA information and application resources')}</div></div></section>
    <section class="section compact-section"><div class="container"><h3>A welcoming school community</h3><p class="policy-text">Trinity’s admissions policy welcomes students regardless of race, creed, color, sex, national origin, or ethnic origin. For the school’s complete nondiscrimination statement and policies, please <a href="${official}/admissions">read the official admissions information</a>.</p></div></section>${visit()}`
  },
  'parents.html': {
    title: 'Parent Resources | FACTS, Supplies, Uniforms & Handbook', description: 'Find Trinity’s FACTS Family Portal, school supply lists, uniform codes, parent student handbook, and calendar in one place.', nav: 'parents',
    content: `${pageIntro('For the Trinity family','School essentials.<br>All in one place.','A convenient starting point for the resources your family uses throughout the school year.')}
    <section class="section"><div class="container"><div class="portal-panel"><div><p class="eyebrow">FACTS Family Portal</p><h2>Stay connected<br>to your child’s school day.</h2><p>Access grades, attendance, homework, and communication with school staff through the school’s secure parent portal.</p></div>${button(portal,'Open FACTS Family Portal')}</div><div class="section-heading resources-heading"><div><p class="eyebrow">Everyday information</p><h2>Family resources</h2></div></div><div class="resource-list">${resource('calendar.html','School calendar','The 2026–2027 calendar, key dates, and a printable copy.','calendar','View calendar')}${resource(`${official}/_files/ugd/1d36c7_af865089cba34a39bbb8ecdddc87c341.pdf`,'Parent / Student Handbook','2025–2026 handbook. Confirm the current version with the office.','book','Open PDF')}${resource(`${official}/_files/ugd/1d36c7_c62436f6f6a244d78cd77b54befbad7d.pdf`,'Uniform code · Pre-K–Grade 4','Dress and everyday uniform requirements for preschool through fourth grade.','file','Open PDF')}${resource(`${official}/_files/ugd/1d36c7_a3d96897bcce48c08f75fe2d527d95d1.pdf`,'Uniform code · Grades 5–8','Dress and everyday uniform requirements for fifth through eighth grade.','file','Open PDF')}${resource('admissions.html#tuition','Tuition & fees','2026–2027 tuition, enrollment, and extended enrichment.','file','View tuition')}</div></div></section>
    <section class="section soft-section" id="supplies"><div class="container content-grid"><div><p class="eyebrow">Prepare for the year</p><h2>School supply lists</h2><p>Choose your child’s grade to open the school’s published 2026–2027 supply list.</p></div><div class="supply-grid">${[
      ['Kindergarten','1acd357908f048e596160cccdd75be71'],['Grade 1','6c1118079335461bb7eb66ef3e9f5b6f'],['Grade 2','d355ff5c66bb49fd897a2c54df8100cd'],['Grades 3 & 4','398b19e96a44449ab73399cc80ea47b2'],['Grades 5 & 6','913efdd36d4a4cc399035a9d0f0c78b9'],['Grades 7 & 8','06b651a0ce084192a509057c3cd67740']
    ].map(([name,id]) => `<a class="supply-link" href="${official}/_files/ugd/1d36c7_${id}.pdf">${icon('file')}<strong>${name}</strong><span>2026–2027 · PDF supply list</span></a>`).join('')}</div></div></section>
    <section class="section"><div class="container notice"><div><h2>Need help finding something?</h2><p>The school office can help with portal access, school documents, or a question about your child’s program.</p></div>${button('contact.html','Contact the school')}</div></section>`
  },
  'calendar.html': {
    title: 'School Calendar | 2026–2027', description: 'View Trinity Episcopal School’s 2026–2027 calendar, key school closure dates, conferences, and a printable calendar.', nav: 'calendar',
    content: `${pageIntro('The school year at a glance','2026–2027<br>school calendar.','Important school dates, planned closures, and the school’s published calendar.')}<section class="section"><div class="container calendar-grid"><div><p class="eyebrow">Plan ahead</p><h2>Key dates</h2><div class="date-list">${[
      ['Aug 12, 2026','First day of school'],['Oct 9, 2026','Parent conferences · No Pre-K; half day for K–8'],['Oct 12–16, 2026','School closed'],['Nov 23–27, 2026','School closed'],['Dec 21, 2026–Jan 1, 2027','School closed'],['Jan 4, 2027','Teacher inservice'],['Jan 18, 2027','School closed'],['Feb 15, 2027','School closed'],['Mar 8–12, 2027','School closed'],['Mar 26 & 29, 2027','School closed'],['Apr 16, 2027','Parent conferences · No Pre-K; half day for K–8'],['May 19, 2027','Last day for Pre-K'],['May 20, 2027','Last day of school'],['May 21, 2027','Teacher inservice']
    ].map(([date,event]) => `<div class="date-row"><span>${date}</span><strong>${event}</strong></div>`).join('')}</div><p class="small-text">Dates are transcribed from the school’s published 2026–2027 calendar. Check the school’s updates for any changes.</p>${link(`${official}/calendar`,'View the calendar on the school website')}</div><aside class="calendar-preview"><p class="eyebrow">The complete school calendar</p><a href="assets/calendar-2026-2027.jpg" aria-label="Open the full-resolution 2026–2027 school calendar"><img src="assets/calendar-2026-2027.jpg" width="1336" height="1888" alt="Trinity’s full 2026–2027 school calendar, including terms, holidays, inservice days, and half days"></a><div class="button-row">${button('assets/calendar-2026-2027.jpg','Open full calendar',true)}<button class="button button-secondary print-button" type="button">Print this page</button></div><p class="small-text">Open the full calendar to view every half day and grading-period date.</p></aside></div></section>`
  },
  'contact.html': {
    title: 'Contact & Tours | Trinity Episcopal School', description: 'Contact Trinity Episcopal School at (903) 938-3513 or mwilliams@trinitymarshall.net. Visit 2905 Rosborough Springs Road, Marshall, TX.', nav: 'contact',
    content: `${pageIntro('Let’s get to know each other','We’d love<br>to meet your family.','Ask a question, find your next step, or arrange a private tour of Trinity Episcopal School.')}<section class="section"><div class="container contact-grid"><div class="contact-details"><div class="contact-item">${icon('phone')}<div><h2>Call the school</h2><a href="tel:+19039383513">(903) 938-3513</a></div></div><div class="contact-item">${icon('mail')}<div><h2>Email the office</h2><a href="${mail}">mwilliams@trinitymarshall.net</a></div></div><div class="contact-item">${icon('pin')}<div><h2>Find us in Marshall</h2><address>2905 Rosborough Springs Road<br>Marshall, TX 75672</address>${link('https://www.google.com/maps/search/?api=1&query=2905+Rosborough+Springs+Rd+Marshall+TX+75672','Get directions')}</div></div></div><aside class="tour-panel"><p class="eyebrow">Come see the school</p><h2>Your visit<br>starts here.</h2><p>Give us a call or email the office to arrange your private tour. We’ll help you learn about the programs and answer your family’s questions.</p>${button(tour,'Email to request a tour')}<p class="small-text">This opens your email app. Your visit is scheduled when the school confirms the details with you.</p><hr><h3>Ready to apply?</h3><p>Find application steps, requirements, and tuition on our admissions page.</p>${link('admissions.html','Explore admissions')}</aside></div></section><section class="section soft-section"><div class="container content-grid"><div><p class="eyebrow">Support Trinity</p><h2>Help our<br>school community grow.</h2></div><div class="prose"><p>Support Christian education at Trinity through the school’s existing giving page.</p>${button(give,'Give to Trinity')}</div></div></section>`
  },
  '404.html': {
    title:'Page Not Found | Trinity Episcopal School',description:'Find your way back to Trinity’s programs, admissions, and parent resources.',nav:'',
    content:`${pageIntro('Page not found','Let’s find<br>your next step.','The page you’re looking for may have moved. Return to the home page or contact the school for help.')}<section class="section"><div class="container button-row">${button('index.html','Return home')}${button('contact.html','Contact the school',true)}</div></section>`
  }
};

const navItems = [['about','about.html','About'],['programs','programs.html','Programs'],['admissions','admissions.html','Admissions'],['parents','parents.html','For parents'],['calendar','calendar.html','Calendar']];
const esc = str => str.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const logo = `<img src="assets/trinity-mark.png" width="235" height="247" alt="" class="brand-mark"><span class="brand-text"><strong>TRINITY</strong><span>EPISCOPAL SCHOOL</span></span>`;
function layout(filename, page) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><meta name="theme-color" content="#0e2973"><title>${esc(page.title)}</title><meta name="description" content="${esc(page.description)}"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}/${filename === 'index.html' ? '' : filename}"><link rel="icon" type="image/svg+xml" href="favicon.svg"><link rel="stylesheet" href="styles.css?v=${stylesVersion}"><script src="site.js?v=${scriptVersion}" defer></script></head>
<body><a href="#main" class="skip-link">Skip to content</a><div class="utility-bar"><div class="container utility-inner"><span>Marshall, Texas <span class="utility-separator">/</span> Since 1954</span><div><a href="${portal}">FACTS Family Portal</a><a href="${give}">Give to Trinity</a></div></div></div><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="Trinity Episcopal School home">${logo}</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav"><span class="menu-label">Menu</span><span class="menu-lines" aria-hidden="true"></span></button><nav class="main-nav" id="main-nav" aria-label="Main navigation">${navItems.map(([id,url,label]) => `<a href="${url}"${page.nav === id ? ' aria-current="page"' : ''}>${label}</a>`).join('')}${button('contact.html','Visit Trinity')}</nav></div></header><main id="main" tabindex="-1">${page.content}</main><footer class="site-footer"><div class="container footer-grid"><div><a class="brand footer-brand" href="index.html" aria-label="Trinity Episcopal School home">${logo}</a><p>Educating the mind, body, and spirit<br>in Marshall, Texas since 1954.</p><address>2905 Rosborough Springs Road<br>Marshall, TX 75672</address></div><div><h2>Explore Trinity</h2><a href="about.html">Our mission &amp; story</a><a href="programs.html">Preschool &amp; K–8</a><a href="admissions.html">Admissions &amp; tuition</a><a href="contact.html">Visit our school</a></div><div><h2>For our families</h2><a href="${portal}">FACTS Family Portal</a><a href="parents.html">Parent resources</a><a href="calendar.html">School calendar</a><a href="${give}">Support Trinity</a></div><div><h2>Get in touch</h2><a href="tel:+19039383513">(903) 938-3513</a><a class="footer-email" href="${mail}">mwilliams@trinitymarshall.net</a><a href="${tour}">Schedule a private tour</a></div></div><div class="container footer-bottom"><span>Trinity Episcopal School</span><span>Redesign proposal · For school review</span><a href="${official}/">Current school website</a></div></footer></body></html>`;
}
for (const [filename,page] of Object.entries(pages)) await writeFile(`${root}${filename}`, layout(filename,page));
await writeFile(`${root}robots.txt`, 'User-agent: *\nDisallow: /\n');
console.log(`Built ${Object.keys(pages).length} pages.`);
